version: 0.2

phases:
  install:
    commands:
      - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      - chmod +x ~/miniconda.sh
      - ~/miniconda.sh -b -u
      - ~/miniconda3/bin/conda env create -q -n customenv --file ./imdbscraper/conf/conda.yml
      - ~/miniconda3/envs/customenv/bin/pytest
  build:
    commands:
      - pytest
  post_build:
    commands:
      - echo Build completed on `date`
