name: Python Package Publish

on:
  push:
    branches:
      - master
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel twine setuptools colorama build
      - name: Install environment
        run: |
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pipenv run pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          files: junit/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
      - name: Build and publish
        if: ${{ success() }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          python -m twine upload dist/* --skip-existing
